# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aeea8b55e764de7a7400b800061238874e9d6185a5b4edf755073cdfc989d7508dba0144517131101fcffbac4d68966055ec2f12fedb37d456f86f31e288a933

test:
  secret_key_base: 687a73962d69eca0464e4949e0c397fae7742b277c50b9ef285efcedeb30cb5cdc867247e2f819550122839ed4d0a8738c7351ff62f0af451a6b13c5462cbc90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
